### ISSUE TITLE
[Firmware feature request][SEN55] Get raw values for VOC and NOx

### ISSUE THREAD

**Issue by sergiuszm** [Sensirion/python-i2c-sen5x#2]
Hi,

Is there a chance to get raw VOC and NOx values that are used to calculate indexes? I own a few sen55 sensors but I am not really happy with index values and the way they are calculated. 

I am aware it requires changes to the firmware but it would be nice to have these values in addition to the indexes.

**Comment by quentin-cy** [comment]
Hello @sergiuszm,
We heard you request. I am looking internally if we can do something about it.
I will keep you up to date in the following days.
Cheers

**Comment by quentin-cy** [comment]
Hello @sergiuszm,

I am now allowed to tell you that this feature is already available in the software. 
It is not advertised because we would prefer people to use the Index value.

You will find the required documentation to query raw values on [Sensirion's website](https://sensirion.com/media/documents/2B6FC1F3/6409E74A/PS_AN_Read_RHT_VOC_and_NOx_RAW_signals_D1.pdf).

Let us know if you need further help.

Cheers,
Q

**Comment by sergiuszm** [comment]
Thanks a lot! :)

Cheers,
Sergiusz
